# Keyboard keys mapped by gptokeyb on muOS (mpvplayer.gptk)
[ playlist-prev
] playlist-next
a cycle-values video-aspect-override "-1" "1:1" "4:3" "3:2" "16:9" "2.35:1"
A cycle-values panscan 0.0 0.5 1.0
v cycle audio
O cycle-values osd-level 1 3
Shift+UP seek 900
Shift+DOWN seek -900
Shift+LEFT add chapter -1
Shift+RIGHT add chapter 1
P screenshot video

# Clamshell controls
INS set pause yes

# Keyboard keys mapped by gptokeyb for Portmaster (xmplayer.gptk)
ENTER cycle pause
BS frame-step
x cycle mute
y no-osd cycle-values osd-level 3 1
LEFT seek -5
RIGHT seek 5
UP seek 60
DOWN seek -60
PGUP playlist-prev
PGDWN playlist-next
l cycle audio
e cycle sub
z cycle-values video-aspect-override "-1" "1:1" "4:3" "3:2" "16:9" "2.35:1"
SPACE quit
Shift+ENTER screenshot video