fs=yes

cursor-autohide=always         
border=no                      

osd-bar=yes                    
osd-bar-align-y=0.6              
osd-bar-w=80                  
osd-bar-h=5                  
osd-border-size=0              

osd-font='Inter'               
osd-font-size=52
osd-border-size=3

osd-level=1                    
osd-duration=3000

screenshot-template="%xscreenshots/Screenshot-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"
